### PR TITLE
Simplify the engine requirements for easier maintenance

### LINKED ISSUE #41: Node version limit
Hello, 

I tried to install the package on my node/express project but I got an error because my version node version (16.x.x or 17.x.x) is not supported. Right now node 16 version isLTS but I think you could have just a minimum version of node support, and not a range.

Thank you.

### PR DESCRIPTION
**Pull request by adamjmcgrath**
@panva wdyt?

fixes #41

### CODE REVIEW

**Comment by panva** [comment]
@adamjmcgrath This would be incorrect.

From https://github.com/panva/jose/issues/262

> Node.js LTS versions ^12.19.0 (Erbium), ^14.15.0 (Fermium), and ^16.13.0 (Gallium) are supported. Future LTS versions will be supported as soon as they get released.

**Comment by adamjmcgrath** [comment]
> Node.js versions that are odd-numbered, or even-numbered before they become Active LTS, may work fine

Do you think it's reasonable to relax the engine requirements for this SDK so we don't have to keep updating it every 6 months?

**Comment by panva** [comment]
> > Node.js versions that are odd-numbered, or even-numbered before they become Active LTS, may work fine
> 
> Do you think it's reasonable to relax the engine requirements for this SDK so we don't have to keep updating it every 6 months?

A new LTS release is cut every 12 months. I'd stick with just LTS releases as that is what our dependency actually guarantees support for.

**Comment by adamjmcgrath** [comment]
Will do 👍

**Pull request closed without merging**
